name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install base
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy files to server
        run: scp -P ${{ secrets.SSH_PORT}} -o StrictHostKeyChecking=no -r ./_site/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:${{ secrets.SSH_PATH }}
